### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by sivailango** [julienrf/play-jsmessages#36]
Hi,

I have tried to implement js messages to my project. To implement it, i added "org.julienrf" %% "play-jsmessages" % "2.0.0" on my build.sbt file. But i am getting 

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::  org.julienrf#play-jsmessages_2.11;2.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.julienrf#play-jsmessages_2.11;2.0.0: not found

May i know how to implement this one?

**Comment by sivailango** [comment]
Fixed the issue by adding "org.julienrf" %% "play-jsmessages" % "1.6.2" on build sbt

**Comment by julienrf** [comment]
The 2.0.0 is not published yet. Are you using Play 2.4 ?
