### ISSUE TITLE
Help - cant generate or access resultant window.Messages object

### ISSUE THREAD

**Issue by gtessler24** [julienrf/play-jsmessages#39]
Help.

Under play 2.3.8, I can not seem to see the window.Messages  object in the browser after following your documentation.

Can you provide a working sample for scala and paly 2.3.8?

Thanks

**Comment by julienrf** [comment]
Hi, you can have a look at the one provided in this repository: https://github.com/julienrf/play-jsmessages/tree/1.6.2/sample-scala
