### ISSUE TITLE
Error trying to use your library.

### ISSUE THREAD

**Issue by gtessler24** [julienrf/play-jsmessages#40]
Can you help me please.  For the life of me, I can not get past this error using your library.  
Thank you.

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9002
[info]
[info] (Server started, use Ctrl+D to stop and go back to the console...)
[info]
[info] Compiling 3 Scala sources to C:\Junk\dev\helloWorldFull\angularJsRequireJ
sFull\target\scala-2.11\classes...
[error] C:\Junk\dev\helloWorldFull\angularJsRequireJsFull\app\views\index.scala.
html:6: identifier expected but ')' found.
[error] @mainMini( title = "Home", strCurrentLanguage="en-US", strCommaListOfLan
gs="en-US,es-MX", strCurrentLanguageJs="aaaLanJs" )(implicit messages: Messages
=>)
[error]

// file Application.scala
package controllers

import play.api._
import play.api.mvc._
import play.api.Play
import play.api.Logger

import jsmessages.JsMessagesFactory
import javax.inject.Inject

import play.api.Play.current							// https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.Play$
import play.api.i18n.{I18nSupport, Messages, MessagesApi, Lang}

import play.api.mvc.{Action, Controller}

class Application ( jsMessagesFactory: JsMessagesFactory, val messagesApi: MessagesApi ) extends Controller with I18nSupport {

	val messages  = jsMessagesFactory.all			// https://github.com/julienrf/play-jsmessages/blob/master/sample-scala/app/controllers/Application.scala

	val jsMessages = Action { implicit request =>
							Ok( messages( Some( "window.Messages" ) ) )
							}

	def index() = Action { request =>

		Ok( views.html.mainMini( "mytitle", "aaa2", "aaa3", "aaa4" ))			// .mainMini is our mainMini.scala.	html file
	 }
}

@*************************************
* mainMini page.                      
*                                   
* @param aaamsg The message to display 
*************************************@
@mainMini( title = "Home", strCurrentLanguage="en-US", strCommaListOfLangs="en-US,es-MX", strCurrentLanguageJs="aaaLanJs" )(implicit messages: Messages =>)

@*************************************
 * mainMini page.
 *
 * @param title - Page title
 * @param strCurrentLanguage - String,
 * @param strCommaListOfLangs - String,
 * @param strCurrentLanguageJs - String
* aaaa (title: String, strCurrentLanguage: String, strCommaListOfLangs : String, strCurrentLanguageJs: String )(implicit messages: Messages)
*************************************@
@(title: String, strCurrentLanguage: String, strCommaListOfLangs : String, strCurrentLanguageJs: String )(implicit messages: Messages)

<!DOCTYPE html>
<html>
<head>
  <title> @title </title>
</head>

<body>
	<div>
		My App Name: aaaAT messages( "application.name" )
	</div>
	<div>
		strCommaListOfLangs @strCommaListOfLangs
	</div>
		<div>
			strCurrentLang @strCurrentLanguage
		</div>
		<div>
			strCurrentLangJs @strCurrentLanguageJs
		</div>
		
	</div>
</body>
</html>

**Comment by julienrf** [comment]
Hi, the error seems to be in `index.scala.html`. You should try posting your problem in the Play mailing list.

**Comment by gtessler24** [comment]
the issue is that I dont know how to use your library.  can you post a better example?

**Comment by julienrf** [comment]
Do you have a more detailed question? What 's wrong with the actual samples?

**Comment by gtessler24** [comment]
see my 1st post:

info] Compiling 3 Scala sources to C:\Junk\dev\helloWorldFull\angularJsRequireJ
sFull\target\scala-2.11\classes...
[error] C:\Junk\dev\helloWorldFull\angularJsRequireJsFull\app\views\index.scala.
html:6: identifier expected but ')' found.
[error] @mainMini( title = "Home", strCurrentLanguage="en-US", strCommaListOfLan
gs="en-US,es-MX", strCurrentLanguageJs="aaaLanJs" )(implicit messages: Messages
=>)
[error]

// file Applicat

I can not get your library to work with "implicit".  can you write a demo for play 2.4 that uses implicit?

**Comment by julienrf** [comment]
As I said in my first comment, it seems that your error comes from the index template.

**Comment by gtessler24** [comment]
indeed for the the issue is how I am trying to use you rlibrary.  I need a non-implicit example.
