### ISSUE TITLE
Play 2.5 compatible version?

### ISSUE THREAD

**Issue by kipsigman** [julienrf/play-jsmessages#42]
Is there any plan to release a new version compatible with Play 2.5? I'd be happy to fork and do a pull request if you like.

**Comment by julienrf** [comment]
Hi, yes a PR would be highly appreciated :)

**Comment by kipsigman** [comment]
Julien - I ended up just copying the code to my https://github.com/kipsigman/play-extensions project, which also makes routes and config available to JavaScript files. I gave you recognition. Would you like to deprecate your project and help me with the play-extensions as it has additional features?

**Comment by julienrf** [comment]
Well, I’m not opposed to transfer this project to someone else, but I must confess that I don’t like the fact that play-extensions mixes several unrelated things, I’d rather see the play-jsmessage project to be independent.

**Comment by kipsigman** [comment]
Here are my thoughts:

* I agree with you, my play-extensions is too broad and not well defined - it's a catch-all bucket for any extra Play stuff that I needed.

* I love your play-jsmessages project, but I think the scope is too narrow. I think it should exist with any other resources needed for JavaScript such as config and routes. For my vision, see https://github.com/kipsigman/play-extensions/blob/master/src/main/scala/kipsigman/play/mvc/JavaScriptResourceController.scala.

I propose this:

1. We create a new joint project for all JavaScript resources, starting with what we have (config, messages, routes). I have no problem putting this project under your user, as you spearheaded this effort and I modeled my work off your project. Or we can create a new organization for combined Play extensions that you, myself, and others can contribute to.

2. You deprecate play-jsmessages, replacing it with the project in item 1.

3. I'll remove all JavaScript functionality from my play-extensions project and reference our new project in my README.


I hope I'm not stepping on your toes here, I'm just hoping to use your great project as a foundation for something with slightly expanded scope that may help Play users. Please let me know your thoughts.

**Comment by julienrf** [comment]
Hi,

I like your idea. Would you agree to proceed as follows? You fork play-jsmessage under the playframework organization (or under your own account, if that’s not possible), so that we keep the git history and I can transfer the project ownership to the new organization (so that users will automatically be redirected to the new project).
